### ISSUE TITLE
Document queries over websocket

### ISSUE THREAD

**Issue by gottfrois** [annkissam/common_graphql_client#20]
Hey folks, unless I completely missed it, there are no documentations about how to perform GQL queries over the websocket server rather than the HTTP. From my understanding, performing a query over websocket is async rather than sync. How to you get the query response then?

Thanks!

**Comment by ericsullivan** [comment]
The configuration I usually use is this:
```
  query_caller: CommonGraphQLClient.Caller.Http,
  subscription_caller: CommonGraphQLClient.Caller.WebSocket,
```

But you can also use the WebSocket as the query_caller. AbsintheWebSocket.QueryServer takes care of making the async calls look like they're sync

**Comment by gottfrois** [comment]
Thanks @ericsullivan, it makes more sense now. I also came across the following blog post which explains the implementation design behind https://www.annkissam.com/elixir/alembic/posts/2018/07/30/genserver-reply.html
